name: grpc-rest-solution

services:
  grpcserviceclient:
    image: ${DOCKER_REGISTRY-}grpcserviceclient:docker
    build:
      context: .
      dockerfile: GrpcServiceClient/Dockerfile

  restserviceclient:
    image: ${DOCKER_REGISTRY-}restserviceclient:docker
    build:
      context: .
      dockerfile: RestServiceClient/Dockerfile
