name: grpc-rest-solution

services:
  grpcserviceclient:
    image: ${DOCKER_REGISTRY-}grpcserviceclient
    build:
      context: .
      dockerfile: GrpcServiceClient/Dockerfile
    # networks:
    #   - POC-GrpcRest

  restserviceclient:
    image: ${DOCKER_REGISTRY-}restserviceclient
    build:
      context: .
      dockerfile: RestServiceClient/Dockerfile
#     networks:
#       - POC-GrpcRest

# networks:
#   POC-GrpcRest:
#     driver: bridge

